apiVersion: apps/v1
kind: Deployment

metadata:
  name: payment-deployment
  labels:
    run: payment
    app: banking-payment

spec:
  replicas: 1
  selector:
    matchLabels:
      run: payment

  template:
    metadata:
      labels:
        run: payment
        app: banking-payment
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "payment"
        dapr.io/app-port: "8080"
    spec:
      containers:
        - name: payment
          image: azrulhasni/payment
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
